# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Medichatbot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://medchatbot.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_69edecb3090d4206949db5be0c6ffa2d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_14ce407b6dc14ed8a877eaaa36088b37 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: medchatbot.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_69edecb3090d4206949db5be0c6ffa2d }}/medichat:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Medichatbot'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_809aed73626242cfa6fbefcde093ba3b }}
        images: 'medchatbot.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_69edecb3090d4206949db5be0c6ffa2d }}/medichat:${{ github.sha }}'